/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import JSwingComponent.JButtonComponent;
import JSwingComponent.JLabelComponent;
import JSwingComponent.JPanelComponent;
import JSwingComponent.JTextFieldComponent;
import JSwingFactory.JButtonFactory;
import JSwingFactory.JLabelFactory;
import JSwingFactory.JPanelFactory;
import JSwingFactory.JSwingComponentFactory;
import JSwingFactory.JTextFieldFactory;

/**
 *
 * @author 源��옱愿�
 */
public class MainFrame extends JFrame {

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void setPanelComponents() {

		tab_sl = panelFactory.panelCreate();
		pnl_gInfo = panelFactory.panelCreate(BorderFactory.createTitledBorder("Gas Information"));
		pnl_sl = panelFactory.panelCreate(BorderFactory.createTitledBorder("Sale"));
		pnl_cInfo = panelFactory.panelCreate(BorderFactory.createTitledBorder("Customer Information"));
		tab_chk = panelFactory.panelCreate();
		pnl_chk = panelFactory.panelCreate(BorderFactory.createTitledBorder("Check When"));
		pnl_res = panelFactory.panelCreate(BorderFactory.createTitledBorder("Result"));
		tab_prc = panelFactory.panelCreate();
		pnl_prc = panelFactory.panelCreate(BorderFactory.createTitledBorder("Change Price"));
		pnl_odr = panelFactory.panelCreate(BorderFactory.createTitledBorder("Order"));

	}

	private void setButtonComponents() {
		btn_ok_sl = buttonFactory.buttonCreate("OK");
		btn_cncl_sl = buttonFactory.buttonCreate("Cancel");
		btn_chk_cInfo = buttonFactory.buttonCreate("Check");
		btn_enrl_cInfo = buttonFactory.buttonCreate("Enroll");
		btn_chk_chk = buttonFactory.buttonCreate("Check");
		btn_chg_prc = buttonFactory.buttonCreate("Change");
		btn_cncl_prc = buttonFactory.buttonCreate("cancel");
		btn_odr_odr = buttonFactory.buttonCreate("Order");
		btn_cncl_odr = buttonFactory.buttonCreate("Cancel");
	}

	private void setTextFieldComponents() {
		txt_vol_sl = textFieldFactory.textFieldCreate("01", JTextField.CENTER, BorderFactory.createEtchedBorder(),
				false);
		txt_mn_sl = textFieldFactory.textFieldCreate("01", JTextField.CENTER, BorderFactory.createEtchedBorder(),
				false);
		txt_stat_ginfo = textFieldFactory.textFieldCreate(" Enough Gas for all kinds", JTextField.CENTER,
				BorderFactory.createEtchedBorder(), false);
		txt_mlg_sl = textFieldFactory.textFieldCreate("00", JTextField.CENTER, BorderFactory.createEtchedBorder(),
				true);
		txt_nm_cInfo = textFieldFactory.textFieldCreate("txt_nm_cInfo", null, BorderFactory.createEtchedBorder(),
				false);
		txt_nmbr_cInfo = textFieldFactory.textFieldCreate("txt_nmbr_cInfo", null, BorderFactory.createEtchedBorder(),
				false);
		txt_mlg_cInfo = textFieldFactory.textFieldCreate("txt_mlg_cInfo", null, BorderFactory.createEtchedBorder(),
				false);
		txt_frm_chk = textFieldFactory.textFieldCreate("19900417", JTextField.CENTER,
				BorderFactory.createEtchedBorder(), false);
		txt_to_chk = textFieldFactory.textFieldCreate("20151117", JTextField.CENTER, BorderFactory.createEtchedBorder(),
				false);

		txt_vol_res = textFieldFactory.textFieldCreate("txt_vol_res", null, BorderFactory.createEtchedBorder(), false);
		txt_sum_res = textFieldFactory.textFieldCreate("txt_vol_res", null, BorderFactory.createEtchedBorder(), false);
		txt_crnt_prc = textFieldFactory.textFieldCreate("txt_crnt_prc", null, BorderFactory.createEtchedBorder(),
				false);
		txt_nw_prc = textFieldFactory.textFieldCreate("txt_crnt_prc", null, BorderFactory.createEtchedBorder(), false);
		txt_crnt_odr = textFieldFactory.textFieldCreate("txt_crnt_prc", null, BorderFactory.createEtchedBorder(),
				false);
		txt_add_odr = textFieldFactory.textFieldCreate("txt_crnt_prc", null, BorderFactory.createEtchedBorder(), false);
	}

	private void setLabelComponents() {
		lbl_type_gInfo = labelFactory.labelCreate("Kind of Gas");

		lbl_vol_gInfo = labelFactory.labelCreate("Remain Volume");
		lbl_prc_gInfo = labelFactory.labelCreate("Price");
		lbl_gsln_gInfo = labelFactory.labelCreate("  Regular :");
		lbl_lpg_gInfo = labelFactory.labelCreate("Premium :");
		lbl_dsl_gInfo = labelFactory.labelCreate("    Diesel :");
		lbl_gslnL_gInfo = labelFactory.labelCreate("L");

		lbl_lpgL_gInfo = labelFactory.labelCreate("L");
		lbl_dslL_gInfo = labelFactory.labelCreate("L");
		lbl_gslnD_gInfo = labelFactory.labelCreate("$");
		lbl_lpgD_gInfo = labelFactory.labelCreate("$");
		lbl_dslD_gInfo = labelFactory.labelCreate("$");

		lbl_gslnPL_gInfo = labelFactory.labelCreate("/ L");
		lbl_lpgPL_gInfo = labelFactory.labelCreate("/ L");
		lbl_dslPL_gInfo = labelFactory.labelCreate("/ L");

		brdr_lpgVol_gInfo = labelFactory.labelCreate("10000", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());
		brdr_dslVol_gInfo = labelFactory.labelCreate("10000", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());
		brdr_gslnVol_gInfo = labelFactory.labelCreate("00", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());
		brdr_gslnPrc_gInfo = labelFactory.labelCreate("00", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());
		brdr_lpgPrc_gInfo = labelFactory.labelCreate("00", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());
		brdr_dslPrc_gInfo = labelFactory.labelCreate("00", SwingConstants.RIGHT, BorderFactory.createEtchedBorder());

		lbl_type_sl = labelFactory.labelCreate("Kind of Gas");
		lbl_mnD_sl = labelFactory.labelCreate("$");

		lbl_volL_sl = labelFactory.labelCreate("L");
		lbl_nm_cInfo = labelFactory.labelCreate("Name");
		lbl_nmbr_cInfo = labelFactory.labelCreate("Number");

		lbl_mlg_cInfo = labelFactory.labelCreate("Mileage");
		lbl_to_chk = labelFactory.labelCreate("To");

		lbl_type_res = labelFactory.labelCreate("Kind of Gas");
		lbl_vol_res = labelFactory.labelCreate("Volume", SwingConstants.CENTER, null);
		lbl_sum_res = labelFactory.labelCreate("Sum", SwingConstants.CENTER, null);
		lbl_sumD_res = labelFactory.labelCreate("$");
		lbl_volL_res = labelFactory.labelCreate("L");

		lbl_type_prc = labelFactory.labelCreate("Kind of Gas");
		lbl_crnt_prc = labelFactory.labelCreate("Current Price (/L)");
		lbl_nw_prc = labelFactory.labelCreate("New Price (/L)");
		lbl_chg_prc = labelFactory.labelCreate("Sure to Change?");

		lbl_type_odr = labelFactory.labelCreate("Kind of Gas");
		lbl_crnt_odr = labelFactory.labelCreate("Current Volume");
		lbl_add_odr = labelFactory.labelCreate("How much litter");
		lbl_chk_odr = labelFactory.labelCreate("Sure to Order?");
		lbl_wlcm = labelFactory.labelCreate("Welcome to Gas Manger!!");
		lbl_date = labelFactory.labelCreate("Today is " + getCurrentDate());
	}

	private void setOtherComponents() {
		tabbedPane = new JTabbedPane();
		cmb_type_sl = new JComboBox<>();
		rd_mn_sl = new JRadioButton();
		rd_vol_sl = new JRadioButton();
		chk_mlg_sl = new JCheckBox();
		// 이호일 버튼 묶기 151203
		ButtonGroup bg_chk = new ButtonGroup();
		bg_chk.add(rd_date_chk = new JRadioButton());
		bg_chk.add(rd_mnth_chk = new JRadioButton());
		bg_chk.add(rd_prd_chk = new JRadioButton());
		bg_chk.add(rd_frmTo_chk = new JRadioButton());
		bg_chk.add(rd_tdy_chk = new JRadioButton());
		cmb_yy_chk = new JComboBox<>();
		cmb_mm_chk = new JComboBox<>();
		cmb_dd_chk = new JComboBox<>();
		cmb_frm_chk = new JComboBox<>();
		cmb_to_chk = new JComboBox<>();
		cmb_type_res = new JComboBox<>();
		cmb_type_prc = new JComboBox<>();
		chk_y_prc = new JCheckBox();
		cmb_type_odr = new JComboBox<>();
		chk_y_odr = new JCheckBox();
		// db_obs = new DB_Observable();

	}

	private String getCurrentDate() {
		String currentDate;
		long tempCurTime = System.currentTimeMillis();
		SimpleDateFormat timeFormat = new SimpleDateFormat("yyyy-MM-dd");
		currentDate = timeFormat.format(new Date(tempCurTime));
		return currentDate;
	}

	private void setCBItems() {

		String[] gasItems = { "Gas", "Regular", "Premium", "Disel" };
		String[] yearItem = { "2015", "2016", "2017" };
		String[] dateItem = new String[31];
		String[] monthItem = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
		for (int i = 0; i < 31; i++) {
			dateItem[i] = String.valueOf(i+1);
		}
		cmb_type_sl.setModel(new DefaultComboBoxModel<>(gasItems));
		cmb_yy_chk.setModel(new DefaultComboBoxModel<>(yearItem));

		cmb_mm_chk.setModel(new DefaultComboBoxModel<>(monthItem));

		cmb_dd_chk.setModel(new DefaultComboBoxModel<>(dateItem));

		cmb_frm_chk.setModel(new DefaultComboBoxModel<>(yearItem));

		cmb_to_chk.setModel(new DefaultComboBoxModel<>(monthItem));

		cmb_type_res.setModel(new DefaultComboBoxModel<>(gasItems));

		cmb_type_prc.setModel(new DefaultComboBoxModel<>(gasItems));

		cmb_type_odr.setModel(new DefaultComboBoxModel<>(gasItems));

	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setButtonComponents();
		setPanelComponents();
		setTextFieldComponents();
		setLabelComponents();
		setOtherComponents();
		setCBItems();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		new JTextField().addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		txt_stat_ginfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		GroupLayout jPanel7Layout = new GroupLayout(pnl_gInfo);
		pnl_gInfo.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addGap(35, 35, 35)
						.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(lbl_gsln_gInfo).addComponent(lbl_type_gInfo).addComponent(lbl_lpg_gInfo)
								.addComponent(lbl_dsl_gInfo))
						.addGap(103, 103, 103)
						.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel7Layout.createSequentialGroup().addComponent(lbl_vol_gInfo).addGap(107,
										107, 107).addComponent(lbl_prc_gInfo))
								.addGroup(jPanel7Layout.createSequentialGroup().addGap(19, 19, 19)
										.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(brdr_lpgVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_lpgL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup().addComponent(
														brdr_gslnVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
														GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_gslnL_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel7Layout.createSequentialGroup().addComponent(
														brdr_dslVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
														GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_dslL_gInfo)))
										.addGap(93, 93, 93)
										.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_dslD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_dslPrc_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_dslPL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_gslnD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_gslnPrc_gInfo, GroupLayout.PREFERRED_SIZE,
																45, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_gslnPL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_lpgD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_lpgPrc_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_lpgPL_gInfo)))
										.addGap(74, 74, 74).addComponent(txt_stat_ginfo, GroupLayout.PREFERRED_SIZE,
												160, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(71, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup().addGap(12, 12, 12)
								.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_type_gInfo).addComponent(lbl_vol_gInfo)
										.addComponent(lbl_prc_gInfo))
								.addGap(18, 18,
										18)
								.addGroup(jPanel7Layout
										.createParallelGroup(GroupLayout.Alignment.LEADING,
												false)
										.addGroup(
												jPanel7Layout.createSequentialGroup()
														.addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_gsln_gInfo)
																		.addComponent(lbl_gslnL_gInfo)
																		.addComponent(brdr_gslnVol_gInfo)
																		.addComponent(lbl_gslnD_gInfo)
																		.addComponent(brdr_gslnPrc_gInfo)
																		.addComponent(lbl_gslnPL_gInfo))
														.addGap(18, 18, 18)
														.addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_lpg_gInfo)
																		.addComponent(brdr_lpgVol_gInfo)
																		.addComponent(lbl_lpgL_gInfo)
																		.addComponent(lbl_lpgD_gInfo)
																		.addComponent(brdr_lpgPrc_gInfo)
																		.addComponent(lbl_lpgPL_gInfo))
														.addGap(20, 20, 20).addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_dsl_gInfo)
																		.addComponent(brdr_dslVol_gInfo)
																		.addComponent(lbl_dslL_gInfo)
																		.addComponent(lbl_dslD_gInfo)
																		.addComponent(brdr_dslPrc_gInfo)
																		.addComponent(lbl_dslPL_gInfo)))
								.addComponent(txt_stat_ginfo)).addGap(0, 45, Short.MAX_VALUE)));

		rd_mn_sl.setText("By Money");
		rd_mn_sl.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);

			}
		});

		rd_vol_sl.setText("By Volume");

		chk_mlg_sl.setText("Use Mileage");

		GroupLayout jPanel8Layout = new GroupLayout(pnl_sl);
		pnl_sl.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup().addGap(34, 34, 34)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel8Layout.createSequentialGroup().addGap(21, 21, 21)
										.addComponent(btn_ok_sl).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(rd_vol_sl).addComponent(chk_mlg_sl)
										.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addComponent(lbl_type_sl).addComponent(rd_mn_sl)))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
						.addComponent(lbl_mnD_sl, GroupLayout.PREFERRED_SIZE, 7, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel8Layout.createSequentialGroup()
														.addGroup(jPanel8Layout
																.createParallelGroup(GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(txt_mlg_sl)
																.addComponent(cmb_type_sl, 0, GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
												.addComponent(txt_mn_sl, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(txt_vol_sl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbl_volL_sl)).addComponent(btn_cncl_sl))
						.addGap(64, 64, 64)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup().addContainerGap(22, Short.MAX_VALUE)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_sl).addComponent(cmb_type_sl, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_mn_sl, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_mnD_sl).addComponent(txt_mn_sl))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_vol_sl).addComponent(txt_vol_sl).addComponent(lbl_volL_sl))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(chk_mlg_sl).addComponent(txt_mlg_sl, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(btn_ok_sl).addComponent(btn_cncl_sl))));

		btn_chk_cInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		GroupLayout jPanel9Layout = new GroupLayout(pnl_cInfo);
		pnl_cInfo.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createSequentialGroup().addGap(62, 62, 62).addGroup(jPanel9Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel9Layout.createSequentialGroup().addGap(47, 47, 47).addComponent(btn_chk_cInfo)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btn_enrl_cInfo).addGap(12, 12, 12))
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(lbl_nmbr_cInfo, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbl_nm_cInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(lbl_mlg_cInfo, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(txt_nmbr_cInfo, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
										.addComponent(txt_nm_cInfo).addComponent(txt_mlg_cInfo))))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_nm_cInfo).addComponent(txt_nm_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_nmbr_cInfo).addComponent(txt_nmbr_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_mlg_cInfo).addComponent(txt_mlg_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_chk_cInfo).addComponent(btn_enrl_cInfo))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		GroupLayout jPanel4Layout = new GroupLayout(tab_sl);
		tab_sl.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(1, 1, 1)
										.addComponent(pnl_sl, GroupLayout.PREFERRED_SIZE, 399,
												GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(pnl_cInfo, GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
						.addComponent(pnl_gInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
						.addGap(0, 3, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(pnl_gInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(pnl_sl, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
										.addComponent(pnl_cInfo, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))));

		tabbedPane.addTab("Sale", tab_sl);

		rd_tdy_chk.setText("Today");

		rd_date_chk.setText("Date           :");
		rd_date_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton9ActionPerformed(evt);
			}
		});

		rd_mnth_chk.setText("This month");

		rd_prd_chk.setText("Month        :");

		rd_frmTo_chk.setText("From.. To..");
		rd_frmTo_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton12ActionPerformed(evt);
			}
		});

		txt_frm_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField7ActionPerformed(evt);
			}
		});

		txt_to_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		GroupLayout jPanel2Layout = new GroupLayout(pnl_chk);
		pnl_chk.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(32, 32, 32).addGroup(jPanel2Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(rd_tdy_chk)
						.addComponent(rd_mnth_chk)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(rd_date_chk).addGap(18, 18, 18)
								.addComponent(cmb_yy_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(cmb_mm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(cmb_dd_chk, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(rd_prd_chk).addComponent(rd_frmTo_chk))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(cmb_frm_chk, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(cmb_to_chk, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(txt_frm_chk, GroupLayout.PREFERRED_SIZE, 91,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(lbl_to_chk)
												.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(txt_to_chk, GroupLayout.PREFERRED_SIZE, 114,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btn_chk_chk, GroupLayout.PREFERRED_SIZE, 90,
														GroupLayout.PREFERRED_SIZE)))))
						.addGap(50, 50, 50)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(rd_tdy_chk)
						.addGap(10, 10, 10)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_date_chk)
								.addComponent(cmb_yy_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_mm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_dd_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(rd_mnth_chk).addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_prd_chk)
								.addComponent(cmb_frm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_to_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_frmTo_chk)
								.addComponent(txt_frm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_to_chk).addComponent(txt_to_chk, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(35, Short.MAX_VALUE))
				.addGroup(GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btn_chk_chk).addContainerGap()));

		txt_vol_res.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField8ActionPerformed(evt);
			}
		});
		// 이호일 수정 151203
		/*
		 * btn_ok_sl.addActionListener(new java.awt.event.ActionListener() {
		 * public void actionPerformed(java.awt.event.ActionEvent evt) {
		 * db_obs.action(); } }); db_obs.addObserver(brdr_lpgVol_gInfo);
		 * db_obs.addObserver(brdr_dslVol_gInfo);
		 * db_obs.addObserver(brdr_gslnVol_gInfo);
		 */
		GroupLayout jPanel1Layout = new GroupLayout(pnl_res);
		pnl_res.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(55, 55, 55)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_res).addComponent(cmb_type_res, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(183, 183, 183).addComponent(
										lbl_vol_res, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(178, 178, 178)
										.addComponent(txt_vol_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbl_volL_res)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
										.addComponent(lbl_sumD_res)))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_sum_res, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_sum_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(75, 75, 75)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_res).addComponent(lbl_vol_res).addComponent(lbl_sum_res))
						.addGap(26, 26, 26)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_sumD_res)
								.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(cmb_type_res, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(txt_sum_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(txt_vol_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lbl_volL_res)))
						.addContainerGap(43, Short.MAX_VALUE)));

		GroupLayout jPanel5Layout = new GroupLayout(tab_chk);
		tab_chk.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addComponent(pnl_chk, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pnl_res, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addComponent(pnl_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(pnl_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)));

		tabbedPane.addTab("Check", tab_chk);

		chk_y_prc.setText("YES");

		GroupLayout jPanel3Layout = new GroupLayout(pnl_prc);
		pnl_prc.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(39, 39, 39)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_prc).addComponent(cmb_type_prc, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(109, 109, 109)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(txt_crnt_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_crnt_prc).addComponent(btn_chg_prc))
						.addGap(112, 112, 112)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
										.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addComponent(btn_cncl_prc).addComponent(lbl_nw_prc))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
										.addComponent(lbl_chg_prc).addGap(71, 71, 71))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(txt_nw_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(chk_y_prc).addGap(92, 92, 92)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_prc).addComponent(lbl_crnt_prc).addComponent(lbl_nw_prc)
								.addComponent(lbl_chg_prc))
						.addGap(40, 40, 40)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(cmb_type_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_crnt_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_nw_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(chk_y_prc))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_chg_prc).addComponent(btn_cncl_prc))
						.addContainerGap()));

		chk_y_odr.setText("YES");

		GroupLayout jPanel11Layout = new GroupLayout(pnl_odr);
		pnl_odr.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(34, 34, 34)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_odr).addComponent(cmb_type_odr, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(119, 119, 119)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_crnt_odr)
								.addComponent(txt_crnt_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_odr_odr))
						.addGap(123, 123, 123)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel11Layout.createSequentialGroup().addComponent(btn_cncl_odr).addGap(0, 0,
										Short.MAX_VALUE))
								.addGroup(jPanel11Layout.createSequentialGroup().addComponent(lbl_add_odr)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbl_chk_odr).addGap(78, 78, 78))
								.addGroup(jPanel11Layout.createSequentialGroup()
										.addComponent(txt_add_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(chk_y_odr).addGap(98, 98, 98)))));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(27, 27, 27)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_add_odr).addComponent(lbl_chk_odr))
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_odr).addComponent(lbl_crnt_odr)))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(cmb_type_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_crnt_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_add_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(chk_y_odr))
						.addGap(34, 34, 34).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_cncl_odr).addComponent(btn_odr_odr))
						.addContainerGap()));

		GroupLayout jPanel6Layout = new GroupLayout(tab_prc);
		tab_prc.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(
						jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(pnl_prc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(pnl_odr, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
						.addComponent(pnl_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnl_odr, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		tabbedPane.addTab("Price & Order", tab_prc);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addContainerGap(32, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(lbl_wlcm).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbl_date).addGap(50, 50, 50)))));
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_wlcm, GroupLayout.PREFERRED_SIZE, 15,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lbl_date))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
						.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE).addGap(29, 29, 29)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton9ActionPerformed

	private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton12ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton12ActionPerformed

	private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField7ActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField8ActionPerformed

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JSwingComponentFactory labelFactory = new JLabelFactory();
	private JSwingComponentFactory textFieldFactory = new JTextFieldFactory();
	private JSwingComponentFactory panelFactory = new JPanelFactory();
	private JSwingComponentFactory buttonFactory = new JButtonFactory();

	private JButtonComponent btn_chk_chk;
	private JButtonComponent btn_chk_cInfo;
	private JButtonComponent btn_enrl_cInfo;
	private JButtonComponent btn_ok_sl;
	private JButtonComponent btn_cncl_sl;
	private JButtonComponent btn_chg_prc;
	private JButtonComponent btn_cncl_prc;
	private JButtonComponent btn_odr_odr;
	private JButtonComponent btn_cncl_odr;
	private JCheckBox chk_mlg_sl;
	private JCheckBox chk_y_prc;
	private JCheckBox chk_y_odr;
	private JComboBox<String> cmb_type_sl;
	private JComboBox<String> cmb_frm_chk;
	private JComboBox<String> cmb_to_chk;
	private JComboBox<String> cmb_type_res;
	private JComboBox<String> cmb_type_prc;
	private JComboBox<String> cmb_type_odr;
	private JComboBox<String> cmb_yy_chk;
	private JComboBox<String> cmb_mm_chk;
	private JComboBox<String> cmb_dd_chk;
	private JLabelComponent lbl_wlcm;
	private JLabelComponent lbl_gslnL_gInfo;
	private JLabelComponent brdr_lpgVol_gInfo;
	private JLabelComponent lbl_lpgL_gInfo;
	private JLabelComponent brdr_dslVol_gInfo;
	private JLabelComponent lbl_dslL_gInfo;
	private JLabelComponent brdr_gslnVol_gInfo;
	private JLabelComponent lbl_gslnD_gInfo;
	private JLabelComponent lbl_lpgD_gInfo;
	private JLabelComponent lbl_dslD_gInfo;
	private JLabelComponent brdr_gslnPrc_gInfo;
	private JLabelComponent lbl_date;
	private JLabelComponent brdr_lpgPrc_gInfo;
	private JLabelComponent brdr_dslPrc_gInfo;
	private JLabelComponent lbl_gslnPL_gInfo;
	private JLabelComponent lbl_lpgPL_gInfo;
	private JLabelComponent lbl_dslPL_gInfo;
	private JLabelComponent lbl_mnD_sl;
	private JLabelComponent lbl_volL_sl;
	private JLabelComponent lbl_nm_cInfo;
	// private JLabelComponent lbl_type_gInfo;

	private JLabelComponent lbl_type_gInfo;
	private JLabelComponent lbl_nmbr_cInfo;
	private JLabelComponent lbl_mlg_cInfo;
	private JLabelComponent lbl_to_chk;
	private JLabelComponent lbl_type_res;
	private JLabelComponent lbl_vol_res;
	private JLabelComponent lbl_sum_res;
	private JLabelComponent lbl_sumD_res;
	private JLabelComponent lbl_volL_res;
	private JLabelComponent lbl_type_prc;
	private JLabelComponent lbl_crnt_prc;
	private JLabelComponent lbl_vol_gInfo;
	private JLabelComponent lbl_nw_prc;
	private JLabelComponent lbl_chg_prc;
	private JLabelComponent lbl_type_odr;
	private JLabelComponent lbl_crnt_odr;
	private JLabelComponent lbl_add_odr;
	private JLabelComponent lbl_chk_odr;
	private JLabelComponent lbl_prc_gInfo;
	private JLabelComponent lbl_gsln_gInfo;
	private JLabelComponent lbl_lpg_gInfo;
	private JLabelComponent lbl_dsl_gInfo;
	private JLabelComponent lbl_type_sl;
	private JPanelComponent pnl_res;
	private JPanelComponent pnl_odr;
	private JPanelComponent pnl_chk;
	private JPanelComponent pnl_prc;
	private JPanelComponent tab_sl;
	private JPanelComponent tab_chk;
	private JPanelComponent tab_prc;
	private JPanelComponent pnl_gInfo;
	private JPanelComponent pnl_sl;
	private JPanelComponent pnl_cInfo;
	private JRadioButton rd_mn_sl;
	private JRadioButton rd_mnth_chk;
	private JRadioButton rd_prd_chk;
	private JRadioButton rd_frmTo_chk;
	private JRadioButton rd_vol_sl;
	private JRadioButton rd_tdy_chk;
	private JRadioButton rd_date_chk;
	private JTabbedPane tabbedPane;
	private JTextFieldComponent txt_stat_ginfo;
	private JTextFieldComponent txt_crnt_prc;
	private JTextFieldComponent txt_vol_sl;
	private JTextFieldComponent txt_mn_sl;
	private JTextFieldComponent txt_nw_prc;
	private JTextFieldComponent txt_crnt_odr;
	private JTextFieldComponent txt_add_odr;
	private JTextFieldComponent txt_nm_cInfo;
	private JTextFieldComponent txt_nmbr_cInfo;
	private JTextFieldComponent txt_mlg_cInfo;
	private JTextFieldComponent txt_to_chk;
	private JTextFieldComponent txt_mlg_sl;
	private JTextFieldComponent txt_frm_chk;
	private JTextFieldComponent txt_vol_res;
	private JTextFieldComponent txt_sum_res;
	// private DB_Observable db_obs;
	// End of variables declaration//GEN-END:variables
}
