/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import JSwingComponent.JLabelComponent;
import JSwingFactory.JLabelFactory;
import JSwingFactory.JSwingComponentFactory;

/**
 *
 * @author 源��옱愿�
 */
public class MainFrame extends JFrame {

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		JSwingComponentFactory temp = new JLabelFactory();
		tabbedPane = new JTabbedPane();
		tab_sl = new JPanel();
		pnl_gInfo = new JPanel();
		// lbl_type_gInfo = new JLabel();
		lbl_type_gInfo = (JLabelComponent) temp.create("Kind of Gas");
		lbl_vol_gInfo = new JLabel();
		lbl_prc_gInfo = new JLabel();
		lbl_gsln_gInfo = new JLabel();
		lbl_lpg_gInfo = new JLabel();
		lbl_dsl_gInfo = new JLabel();
		lbl_gslnL_gInfo = new JLabel();
		brdr_lpgVol_gInfo = new JLabel();
		lbl_lpgL_gInfo = new JLabel();
		brdr_dslVol_gInfo = new JLabel();
		lbl_dslL_gInfo = new JLabel();
		brdr_gslnVol_gInfo = new JLabel();
		lbl_gslnD_gInfo = new JLabel();
		lbl_lpgD_gInfo = new JLabel();
		lbl_dslD_gInfo = new JLabel();
		brdr_gslnPrc_gInfo = new JLabel();
		brdr_lpgPrc_gInfo = new JLabel();
		brdr_dslPrc_gInfo = new JLabel();
		lbl_gslnPL_gInfo = new JLabel();
		lbl_lpgPL_gInfo = new JLabel();
		lbl_dslPL_gInfo = new JLabel();
		jTextField1 = new JTextField();
		pnl_sl = new JPanel();
		lbl_type_sl = new JLabel();
		cmb_type_sl = new JComboBox<>();
		rd_mn_sl = new JRadioButton();
		rd_vol_sl = new JRadioButton();
		lbl_mnD_sl = new JLabel();
		brdr_vol_sl = new JLabel();
		brdr_mn_sl = new JLabel();
		lbl_volL_sl = new JLabel();
		chk_mlg_sl = new JCheckBox();
		txt_mlg_sl = new JTextField();
		btn_ok_sl = new JButton();
		btn_cncl_sl = new JButton();
		pnl_cInfo = new JPanel();
		lbl_nm_cInfo = new JLabel();
		lbl_nmbr_cInfo = new JLabel();
		txt_nm_cInfo = new JTextField();
		txt_nmbr_cInfo = new JTextField();
		lbl_mlg_cInfo = new JLabel();
		txt_mlg_cInfo = new JTextField();
		btn_chk_cInfo = new JButton();
		btn_enrl_cInfo = new JButton();
		tab_chk = new JPanel();
		pnl_chk = new JPanel();
		rd_tdy_chk = new JRadioButton();
		rd_date_chk = new JRadioButton();
		rd_mnth_chk = new JRadioButton();
		rd_prd_chk = new JRadioButton();
		rd_frmTo_chk = new JRadioButton();
		cmb_yy_chk = new JComboBox<>();
		cmb_mm_chk = new JComboBox<>();
		cmb_dd_chk = new JComboBox<>();
		cmb_frm_chk = new JComboBox<>();
		cmb_to_chk = new JComboBox<>();
		txt_frm_chk = new JTextField();
		lbl_to_chk = new JLabel();
		txt_to_chk = new JTextField();
		btn_chk_chk = new JButton();
		pnl_res = new JPanel();
		lbl_type_res = new JLabel();
		lbl_vol_res = new JLabel();
		lbl_sum_res = new JLabel();
		cmb_type_res = new JComboBox<>();
		txt_vol_res = new JTextField();
		txt_sum_res = new JTextField();
		lbl_sumD_res = new JLabel();
		lbl_volL_res = new JLabel();
		tab_prc = new JPanel();
		pnl_prc = new JPanel();
		lbl_type_prc = new JLabel();
		cmb_type_prc = new JComboBox<>();
		lbl_crnt_prc = new JLabel();
		lbl_nw_prc = new JLabel();
		lbl_chg_prc = new JLabel();
		txt_crnt_prc = new JTextField();
		txt_nw_prc = new JTextField();
		chk_y_prc = new JCheckBox();
		btn_chg_prc = new JButton();
		btn_cncl_prc = new JButton();
		pnl_odr = new JPanel();
		lbl_type_odr = new JLabel();
		cmb_type_odr = new JComboBox<>();
		txt_crnt_odr = new JTextField();
		lbl_crnt_odr = new JLabel();
		lbl_add_odr = new JLabel();
		txt_add_odr = new JTextField();
		lbl_chk_odr = new JLabel();
		chk_y_odr = new JCheckBox();
		btn_odr_odr = new JButton();
		btn_cncl_odr = new JButton();
		lbl_wlcm = new JLabel();
		lbl_date = new JLabel();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		pnl_gInfo.setBorder(BorderFactory.createTitledBorder("Gas Information"));

		// lbl_type_gInfo.setText("Kind of Gas");
		System.out.println(lbl_type_gInfo.getHorizontalAlignment());

		lbl_vol_gInfo.setText("Remain Volume");

		lbl_prc_gInfo.setText("Price");

		lbl_gsln_gInfo.setText("  Regular :");

		lbl_lpg_gInfo.setText("Premium :");

		lbl_dsl_gInfo.setText("    Diesel :");

		lbl_gslnL_gInfo.setText("L");

		brdr_lpgVol_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_lpgVol_gInfo.setText("10000");
		brdr_lpgVol_gInfo.setBorder(BorderFactory.createEtchedBorder());

		lbl_lpgL_gInfo.setText("L");

		brdr_dslVol_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_dslVol_gInfo.setText("10000");
		brdr_dslVol_gInfo.setBorder(BorderFactory.createEtchedBorder());

		lbl_dslL_gInfo.setText("L");

		brdr_gslnVol_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_gslnVol_gInfo.setText("00");
		brdr_gslnVol_gInfo.setBorder(BorderFactory.createEtchedBorder());
		lbl_gslnD_gInfo.setText("$");

		lbl_lpgD_gInfo.setText("$");

		lbl_dslD_gInfo.setText("$");
		brdr_gslnPrc_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_gslnPrc_gInfo.setText("00");
		brdr_gslnPrc_gInfo.setBorder(BorderFactory.createEtchedBorder());

		brdr_lpgPrc_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_lpgPrc_gInfo.setText("00");
		brdr_lpgPrc_gInfo.setBorder(BorderFactory.createEtchedBorder());

		brdr_dslPrc_gInfo.setHorizontalAlignment(SwingConstants.RIGHT);
		brdr_dslPrc_gInfo.setText("00");
		brdr_dslPrc_gInfo.setBorder(BorderFactory.createEtchedBorder());

		lbl_gslnPL_gInfo.setText("/ L");

		lbl_lpgPL_gInfo.setText("/ L");

		lbl_dslPL_gInfo.setText("/ L");

		jTextField1.setEditable(false);
		jTextField1.setHorizontalAlignment(JTextField.CENTER);
		jTextField1.setText(" Enough Gas for all kinds");
		jTextField1.setBorder(BorderFactory.createEtchedBorder());
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		GroupLayout jPanel7Layout = new GroupLayout(pnl_gInfo);
		pnl_gInfo.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addGap(35, 35, 35)
						.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(lbl_gsln_gInfo).addComponent(lbl_type_gInfo).addComponent(lbl_lpg_gInfo)
								.addComponent(lbl_dsl_gInfo))
						.addGap(103, 103, 103)
						.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel7Layout.createSequentialGroup().addComponent(lbl_vol_gInfo).addGap(107,
										107, 107).addComponent(lbl_prc_gInfo))
								.addGroup(jPanel7Layout.createSequentialGroup().addGap(19, 19, 19)
										.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(brdr_lpgVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_lpgL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup().addComponent(
														brdr_gslnVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
														GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_gslnL_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel7Layout.createSequentialGroup().addComponent(
														brdr_dslVol_gInfo, GroupLayout.PREFERRED_SIZE, 45,
														GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_dslL_gInfo)))
										.addGap(93, 93, 93)
										.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_dslD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_dslPrc_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_dslPL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_gslnD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_gslnPrc_gInfo, GroupLayout.PREFERRED_SIZE,
																45, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_gslnPL_gInfo))
												.addGroup(jPanel7Layout.createSequentialGroup()
														.addComponent(lbl_lpgD_gInfo, GroupLayout.PREFERRED_SIZE, 7,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(brdr_lpgPrc_gInfo, GroupLayout.PREFERRED_SIZE, 45,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lbl_lpgPL_gInfo)))
										.addGap(74, 74, 74).addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 160,
												GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(71, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup().addGap(12, 12, 12)
								.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_type_gInfo).addComponent(lbl_vol_gInfo)
										.addComponent(lbl_prc_gInfo))
								.addGap(18, 18,
										18)
								.addGroup(jPanel7Layout
										.createParallelGroup(GroupLayout.Alignment.LEADING,
												false)
										.addGroup(
												jPanel7Layout.createSequentialGroup()
														.addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_gsln_gInfo)
																		.addComponent(lbl_gslnL_gInfo)
																		.addComponent(brdr_gslnVol_gInfo)
																		.addComponent(lbl_gslnD_gInfo)
																		.addComponent(brdr_gslnPrc_gInfo)
																		.addComponent(lbl_gslnPL_gInfo))
														.addGap(18, 18, 18)
														.addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_lpg_gInfo)
																		.addComponent(brdr_lpgVol_gInfo)
																		.addComponent(lbl_lpgL_gInfo)
																		.addComponent(lbl_lpgD_gInfo)
																		.addComponent(brdr_lpgPrc_gInfo)
																		.addComponent(lbl_lpgPL_gInfo))
														.addGap(20, 20, 20).addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.BASELINE)
																		.addComponent(lbl_dsl_gInfo)
																		.addComponent(brdr_dslVol_gInfo)
																		.addComponent(lbl_dslL_gInfo)
																		.addComponent(lbl_dslD_gInfo)
																		.addComponent(brdr_dslPrc_gInfo)
																		.addComponent(lbl_dslPL_gInfo)))
								.addComponent(jTextField1)).addGap(0, 45, Short.MAX_VALUE)));

		pnl_sl.setBorder(BorderFactory.createTitledBorder("Sale"));
		pnl_sl.setPreferredSize(new java.awt.Dimension(709, 173));

		lbl_type_sl.setText("Kind of Gas");

		cmb_type_sl.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		rd_mn_sl.setText("By Money");
		rd_mn_sl.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);

			}
		});

		rd_vol_sl.setText("By Volume");

		lbl_mnD_sl.setText("$");

		brdr_vol_sl.setHorizontalAlignment(SwingConstants.CENTER);
		brdr_vol_sl.setText("00");
		brdr_vol_sl.setBorder(BorderFactory.createEtchedBorder());

		brdr_mn_sl.setHorizontalAlignment(SwingConstants.CENTER);
		brdr_mn_sl.setText("00");
		brdr_mn_sl.setBorder(BorderFactory.createEtchedBorder());

		lbl_volL_sl.setText("L");

		chk_mlg_sl.setText("Use Mileage");

		txt_mlg_sl.setEditable(false);
		txt_mlg_sl.setHorizontalAlignment(JTextField.CENTER);
		txt_mlg_sl.setText("00");

		btn_ok_sl.setText("OK");

		btn_cncl_sl.setText("Cancel");

		GroupLayout jPanel8Layout = new GroupLayout(pnl_sl);
		pnl_sl.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup().addGap(34, 34, 34)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel8Layout.createSequentialGroup().addGap(21, 21, 21)
										.addComponent(btn_ok_sl).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(rd_vol_sl).addComponent(chk_mlg_sl)
										.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addComponent(lbl_type_sl).addComponent(rd_mn_sl)))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
						.addComponent(lbl_mnD_sl, GroupLayout.PREFERRED_SIZE, 7, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel8Layout.createSequentialGroup()
														.addGroup(jPanel8Layout
																.createParallelGroup(GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(txt_mlg_sl)
																.addComponent(cmb_type_sl, 0, GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
												.addComponent(brdr_mn_sl, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(brdr_vol_sl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbl_volL_sl)).addComponent(btn_cncl_sl))
						.addGap(64, 64, 64)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup().addContainerGap(22, Short.MAX_VALUE)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_sl).addComponent(cmb_type_sl, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_mn_sl, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_mnD_sl).addComponent(brdr_mn_sl))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_vol_sl).addComponent(brdr_vol_sl).addComponent(lbl_volL_sl))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(chk_mlg_sl).addComponent(txt_mlg_sl, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(btn_ok_sl).addComponent(btn_cncl_sl))));

		pnl_cInfo.setBorder(BorderFactory.createTitledBorder("Customer Information"));

		lbl_nm_cInfo.setText("Name");

		lbl_nmbr_cInfo.setText("Number");

		txt_nm_cInfo.setText("txt_nm_cInfo");

		txt_nmbr_cInfo.setText("txt_nmbr_cInfo");

		lbl_mlg_cInfo.setText("Mileage");

		txt_mlg_cInfo.setEditable(false);
		txt_mlg_cInfo.setText("txt_mlg_cInfo");
		txt_mlg_cInfo.setBorder(BorderFactory.createEtchedBorder());

		btn_chk_cInfo.setText("Check");
		btn_chk_cInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		btn_enrl_cInfo.setText("Enroll");

		GroupLayout jPanel9Layout = new GroupLayout(pnl_cInfo);
		pnl_cInfo.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createSequentialGroup().addGap(62, 62, 62).addGroup(jPanel9Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel9Layout.createSequentialGroup().addGap(47, 47, 47).addComponent(btn_chk_cInfo)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btn_enrl_cInfo).addGap(12, 12, 12))
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(lbl_nmbr_cInfo, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbl_nm_cInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(lbl_mlg_cInfo, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(txt_nmbr_cInfo, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
										.addComponent(txt_nm_cInfo).addComponent(txt_mlg_cInfo))))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_nm_cInfo).addComponent(txt_nm_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_nmbr_cInfo).addComponent(txt_nmbr_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_mlg_cInfo).addComponent(txt_mlg_cInfo, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_chk_cInfo).addComponent(btn_enrl_cInfo))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		GroupLayout jPanel4Layout = new GroupLayout(tab_sl);
		tab_sl.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(1, 1, 1)
										.addComponent(pnl_sl, GroupLayout.PREFERRED_SIZE, 399,
												GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(pnl_cInfo, GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
						.addComponent(pnl_gInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
						.addGap(0, 3, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(pnl_gInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(pnl_sl, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
										.addComponent(pnl_cInfo, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))));

		tabbedPane.addTab("Sale", tab_sl);

		pnl_chk.setBorder(BorderFactory.createTitledBorder("Check When"));

		rd_tdy_chk.setText("Today");

		rd_date_chk.setText("Date           :");
		rd_date_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton9ActionPerformed(evt);
			}
		});

		rd_mnth_chk.setText("This month");

		rd_prd_chk.setText("Month        :");

		rd_frmTo_chk.setText("From.. To..");
		rd_frmTo_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton12ActionPerformed(evt);
			}
		});

		cmb_yy_chk.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmb_mm_chk.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmb_dd_chk.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmb_frm_chk.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmb_to_chk.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		txt_frm_chk.setEditable(false);
		txt_frm_chk.setHorizontalAlignment(JTextField.CENTER);
		txt_frm_chk.setText("19900417");
		txt_frm_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField7ActionPerformed(evt);
			}
		});

		lbl_to_chk.setText("To");

		txt_to_chk.setEditable(false);
		txt_to_chk.setHorizontalAlignment(JTextField.CENTER);
		txt_to_chk.setText("20151117");
		txt_to_chk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		btn_chk_chk.setText("Check");

		GroupLayout jPanel2Layout = new GroupLayout(pnl_chk);
		pnl_chk.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(32, 32, 32).addGroup(jPanel2Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(rd_tdy_chk)
						.addComponent(rd_mnth_chk)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(rd_date_chk).addGap(18, 18, 18)
								.addComponent(cmb_yy_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(cmb_mm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(cmb_dd_chk, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(rd_prd_chk).addComponent(rd_frmTo_chk))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(cmb_frm_chk, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(cmb_to_chk, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(txt_frm_chk, GroupLayout.PREFERRED_SIZE, 91,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(lbl_to_chk)
												.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(txt_to_chk, GroupLayout.PREFERRED_SIZE, 114,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btn_chk_chk, GroupLayout.PREFERRED_SIZE, 90,
														GroupLayout.PREFERRED_SIZE)))))
						.addGap(50, 50, 50)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(rd_tdy_chk)
						.addGap(10, 10, 10)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_date_chk)
								.addComponent(cmb_yy_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_mm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_dd_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(rd_mnth_chk).addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_prd_chk)
								.addComponent(cmb_frm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(cmb_to_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(rd_frmTo_chk)
								.addComponent(txt_frm_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_to_chk).addComponent(txt_to_chk, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(35, Short.MAX_VALUE))
				.addGroup(GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btn_chk_chk).addContainerGap()));

		pnl_res.setBorder(BorderFactory.createTitledBorder("Result"));

		lbl_type_res.setText("Kind of Gas");

		lbl_vol_res.setHorizontalAlignment(SwingConstants.CENTER);
		lbl_vol_res.setText("Volume");

		lbl_sum_res.setHorizontalAlignment(SwingConstants.CENTER);
		lbl_sum_res.setText("Sum");

		cmb_type_res.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		txt_vol_res.setEditable(false);
		txt_vol_res.setText("txt_vol_res");
		txt_vol_res.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField8ActionPerformed(evt);
			}
		});

		txt_sum_res.setEditable(false);
		txt_sum_res.setText("txt_vol_res");

		lbl_sumD_res.setText("$");

		lbl_volL_res.setText("L");

		GroupLayout jPanel1Layout = new GroupLayout(pnl_res);
		pnl_res.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(55, 55, 55)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_res).addComponent(cmb_type_res, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(183, 183, 183).addComponent(
										lbl_vol_res, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(178, 178, 178)
										.addComponent(txt_vol_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbl_volL_res)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
										.addComponent(lbl_sumD_res)))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_sum_res, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_sum_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(75, 75, 75)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_res).addComponent(lbl_vol_res).addComponent(lbl_sum_res))
						.addGap(26, 26, 26)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_sumD_res)
								.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(cmb_type_res, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(txt_sum_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(txt_vol_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lbl_volL_res)))
						.addContainerGap(43, Short.MAX_VALUE)));

		GroupLayout jPanel5Layout = new GroupLayout(tab_chk);
		tab_chk.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addComponent(pnl_chk, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pnl_res, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addComponent(pnl_chk, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(pnl_res, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)));

		tabbedPane.addTab("Check", tab_chk);

		pnl_prc.setBorder(BorderFactory.createTitledBorder("Change Price"));

		lbl_type_prc.setText("Kind of Gas");

		cmb_type_prc.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lbl_crnt_prc.setText("Current Price (/L)");

		lbl_nw_prc.setText("New Price (/L)");

		lbl_chg_prc.setText("Sure to Change?");

		txt_crnt_prc.setEditable(false);
		txt_crnt_prc.setText("txt_crnt_prc");

		txt_nw_prc.setText("txt_crnt_prc");

		chk_y_prc.setText("YES");

		btn_chg_prc.setText("Change");

		btn_cncl_prc.setText("Cancel");

		GroupLayout jPanel3Layout = new GroupLayout(pnl_prc);
		pnl_prc.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(39, 39, 39)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_prc).addComponent(cmb_type_prc, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(109, 109, 109)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(txt_crnt_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_crnt_prc).addComponent(btn_chg_prc))
						.addGap(112, 112, 112)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addGroup(GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
										.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addComponent(btn_cncl_prc).addComponent(lbl_nw_prc))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
										.addComponent(lbl_chg_prc).addGap(71, 71, 71))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(txt_nw_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(chk_y_prc).addGap(92, 92, 92)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_prc).addComponent(lbl_crnt_prc).addComponent(lbl_nw_prc)
								.addComponent(lbl_chg_prc))
						.addGap(40, 40, 40)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(cmb_type_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_crnt_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_nw_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(chk_y_prc))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_chg_prc).addComponent(btn_cncl_prc))
						.addContainerGap()));

		pnl_odr.setBorder(BorderFactory.createTitledBorder("Order"));

		lbl_type_odr.setText("Kind of Gas");

		cmb_type_odr.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		txt_crnt_odr.setEditable(false);
		txt_crnt_odr.setText("txt_crnt_prc");

		lbl_crnt_odr.setText("Current Volume");

		lbl_add_odr.setText("How much litter");

		txt_add_odr.setText("txt_crnt_prc");

		lbl_chk_odr.setText("Sure to Order?");

		chk_y_odr.setText("YES");

		btn_odr_odr.setText("Order");

		btn_cncl_odr.setText("Cancel");

		GroupLayout jPanel11Layout = new GroupLayout(pnl_odr);
		pnl_odr.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(34, 34, 34)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_type_odr).addComponent(cmb_type_odr, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(119, 119, 119)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(lbl_crnt_odr)
								.addComponent(txt_crnt_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_odr_odr))
						.addGap(123, 123, 123)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel11Layout.createSequentialGroup().addComponent(btn_cncl_odr).addGap(0, 0,
										Short.MAX_VALUE))
								.addGroup(jPanel11Layout.createSequentialGroup().addComponent(lbl_add_odr)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbl_chk_odr).addGap(78, 78, 78))
								.addGroup(jPanel11Layout.createSequentialGroup()
										.addComponent(txt_add_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(chk_y_odr).addGap(98, 98, 98)))));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(27, 27, 27)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_add_odr).addComponent(lbl_chk_odr))
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_type_odr).addComponent(lbl_crnt_odr)))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
						.addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(cmb_type_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_crnt_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(txt_add_odr, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(chk_y_odr))
						.addGap(34, 34, 34).addGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(btn_cncl_odr).addComponent(btn_odr_odr))
						.addContainerGap()));

		GroupLayout jPanel6Layout = new GroupLayout(tab_prc);
		tab_prc.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(
						jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(pnl_prc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(pnl_odr, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
						.addComponent(pnl_prc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnl_odr, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		tabbedPane.addTab("Price & Order", tab_prc);

		lbl_wlcm.setText("Welcome to Gas Manger!!");

		lbl_date.setText("Today is 0000-00-00");

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addContainerGap(32, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(lbl_wlcm).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbl_date).addGap(50, 50, 50)))));
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(lbl_wlcm, GroupLayout.PREFERRED_SIZE, 15,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lbl_date))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
						.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE).addGap(29, 29, 29)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton9ActionPerformed

	private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton12ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton12ActionPerformed

	private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField7ActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField8ActionPerformed

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton btn_chk_chk;
	private JButton btn_chk_cInfo;
	private JButton btn_enrl_cInfo;
	private JButton btn_ok_sl;
	private JButton btn_cncl_sl;
	private JButton btn_chg_prc;
	private JButton btn_cncl_prc;
	private JButton btn_odr_odr;
	private JButton btn_cncl_odr;
	private JCheckBox chk_mlg_sl;
	private JCheckBox chk_y_prc;
	private JCheckBox chk_y_odr;
	private JComboBox<String> cmb_type_sl;
	private JComboBox<String> cmb_frm_chk;
	private JComboBox<String> cmb_to_chk;
	private JComboBox<String> cmb_type_res;
	private JComboBox<String> cmb_type_prc;
	private JComboBox<String> cmb_type_odr;
	private JComboBox<String> cmb_yy_chk;
	private JComboBox<String> cmb_mm_chk;
	private JComboBox<String> cmb_dd_chk;
	private JLabel lbl_wlcm;
	private JLabel lbl_gslnL_gInfo;
	private JLabel brdr_lpgVol_gInfo;
	private JLabel lbl_lpgL_gInfo;
	private JLabel brdr_dslVol_gInfo;
	private JLabel lbl_dslL_gInfo;
	private JLabel brdr_gslnVol_gInfo;
	private JLabel lbl_gslnD_gInfo;
	private JLabel lbl_lpgD_gInfo;
	private JLabel lbl_dslD_gInfo;
	private JLabel brdr_gslnPrc_gInfo;
	private JLabel lbl_date;
	private JLabel brdr_lpgPrc_gInfo;
	private JLabel brdr_dslPrc_gInfo;
	private JLabel lbl_gslnPL_gInfo;
	private JLabel lbl_lpgPL_gInfo;
	private JLabel lbl_dslPL_gInfo;
	private JLabel lbl_mnD_sl;
	private JLabel brdr_vol_sl;
	private JLabel brdr_mn_sl;
	private JLabel lbl_volL_sl;
	private JLabel lbl_nm_cInfo;
	// private JLabel lbl_type_gInfo;

	private JLabelComponent lbl_type_gInfo;
	private JLabel lbl_nmbr_cInfo;
	private JLabel lbl_mlg_cInfo;
	private JLabel lbl_to_chk;
	private JLabel lbl_type_res;
	private JLabel lbl_vol_res;
	private JLabel lbl_sum_res;
	private JLabel lbl_sumD_res;
	private JLabel lbl_volL_res;
	private JLabel lbl_type_prc;
	private JLabel lbl_crnt_prc;
	private JLabel lbl_vol_gInfo;
	private JLabel lbl_nw_prc;
	private JLabel lbl_chg_prc;
	private JLabel lbl_type_odr;
	private JLabel lbl_crnt_odr;
	private JLabel lbl_add_odr;
	private JLabel lbl_chk_odr;
	private JLabel lbl_prc_gInfo;
	private JLabel lbl_gsln_gInfo;
	private JLabel lbl_lpg_gInfo;
	private JLabel lbl_dsl_gInfo;
	private JLabel lbl_type_sl;
	private JPanel pnl_res;
	private JPanel pnl_odr;
	private JPanel pnl_chk;
	private JPanel pnl_prc;
	private JPanel tab_sl;
	private JPanel tab_chk;
	private JPanel tab_prc;
	private JPanel pnl_gInfo;
	private JPanel pnl_sl;
	private JPanel pnl_cInfo;
	private JRadioButton rd_mn_sl;
	private JRadioButton rd_mnth_chk;
	private JRadioButton rd_prd_chk;
	private JRadioButton rd_frmTo_chk;
	private JRadioButton rd_vol_sl;
	private JRadioButton rd_tdy_chk;
	private JRadioButton rd_date_chk;
	private JTabbedPane tabbedPane;
	private JTextField jTextField1;
	private JTextField txt_crnt_prc;
	private JTextField txt_nw_prc;
	private JTextField txt_crnt_odr;
	private JTextField txt_add_odr;
	private JTextField txt_nm_cInfo;
	private JTextField txt_nmbr_cInfo;
	private JTextField txt_mlg_cInfo;
	private JTextField txt_to_chk;
	private JTextField txt_mlg_sl;
	private JTextField txt_frm_chk;
	private JTextField txt_vol_res;
	private JTextField txt_sum_res;
	// End of variables declaration//GEN-END:variables
}
